---
title: "Data Preparation"
params:
  out_dir: "processed/train"
  x_path: "/vsicurl/https://glaciersblob.blob.core.windows.net/glaciersdata-kris/region.vrt"
  y_path: "/vsicurl/https://glaciersblob.blob.core.windows.net/glaciersdata-kris/glaciers.geojson"
  basins: "https://uwmadison.box.com/shared/static/2ptmi9b4gt5d5vyusju5u8kn5n1s6hnd.csv"
  n_patches: 200
  #basins: "https://uwmadison.box.com/shared/static/iilcsf3bbois8tmt7pklriu219s4wlu6.csv" # for test basins
---

```{r setup, include=FALSE}
rm(list=setdiff(ls(), "params"))
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library("RStoolbox")
library("abind")
library("dplyr")
library("gdalUtils")
library("ggplot2")
library("gridExtra")
library("purrr")
library("raster")
library("readr")
library("reticulate")
library("sf")
library("stringr")
library("tidyr")

# setting up python environment
use_condaenv("mappingvis")
np <- import("numpy")
source("data.R")
theme_set(theme_minimal())
set.seed(123)
```

Read geojson.

```{r}
y_path <- file.path(params$y_path)
basins <- read_csv(params$basins)

y <- read_sf(y_path) %>%
  filter(Sub_basin %in% basins$Sub_basin)
```

Get sampling locations.

```{r}
centers <- y %>%
  st_sample(params$n_patches, type = "random", by_polygon = FALSE) %>%
  st_coordinates()
colnames(centers) <- c("Longitude", "Latitude")
p <- ggplot(y, aes(x = Longitude, y = Latitude)) +
  geom_sf(data = y, aes(fill = Glaciers)) +
  geom_point(data = as.data.frame(centers), col = "red", size = 2) +
  scale_fill_manual(values = c("#93b9c3", "#4e326a"))

p
```

Cropped.

```{r}
p + coord_sf(xlim = c(70.7, 71.2),  ylim = c(36.2, 36.5))
```
Example patch.

```{r}
head(y)
y %>%
  filter(Longitude < 94.5, Longitude > 92.1) %>%
  filter(Latitude > 28, Latitude < 29.9)
```


```{r}
vrt_path <- file.path(params$x_path)
ys <- y %>% split(.$Glaciers)
patch <- generate_patch(vrt_path, centers[5, ])
patch_y <- label_mask(ys, patch$raster)
p <- list(
  plot_rgb(brick(patch$x), c(5, 4, 2), r = 1, g = 2, b = 3),
  plot_rgb(brick(patch$x), rep(13, 3)),
  plot_rgb(brick(patch_y), r = NULL)
)
grid.arrange(grobs = p, ncol = 3)
```

Example histogram.

```{r}
sample_ix <- sample(nrow(patch$x), 100)
x_df <- patch$x[sample_ix, sample_ix, ] %>%
  brick() %>%
  as.data.frame() %>%
  pivot_longer(cols = everything())

ggplot(x_df) +
  geom_histogram(aes(x = value)) +
  facet_wrap(~ name, scale = "free_x")
```

Write all results.

```{r}
write_patches(vrt_path, ys, centers, params$out_dir)
```