---
title: "Model Evaluation"
params:
  preds_dir: "/Users/kris/data/predictions/"
  geo_dir: "/Users/kris/data/processed/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = TRUE)
```

```{r}
library("RStoolbox")
library("raster")
library("dplyr")
library("ggplot2")
library("gridExtra")
library("purrr")
library("reticulate")
library("sf")
library("stringr")
library("tidyr")
use_condaenv("notebook")
np <- reticulate::import("numpy")
source("data.R")
source("metrics.R")
theme_set(theme_minimal())
```

```{r}
preds_dir <- params$preds_dir
dir.create(preds_dir)
preds_file <- file.path(preds_dir, "preds.tar.gz")
download.file("https://uwmadison.box.com/shared/static/5s7sqvh50iy5p2yl2basfdzgss9lgnxr.gz", preds_file)
untar(preds_file, exdir = params$preds_dir)
unlink(preds_file)
```

```{r}
paths <- prediction_paths(preds_dir)
head(paths)
```

```{r}
y <- load_npy(paths$path[2])
y_hat <- load_npy(paths$path[3])
p <- list(
  plot_rgb(y, 1, r = NULL, g = NULL, b = 1),
  plot_rgb(y_hat, 1, r = NULL, g = NULL, b = 1)
)
grid.arrange(grobs = p, ncol = 2)
```

```{r, animation.hook="gifski", interval = 0.02}
thresholds <- c(seq(0.05, 0.9, 0.01), rep(0.9, 10))
for (i in seq_along(thresholds)) {
  print(plot_rgb(y_hat > thresholds[i], 1, r = NULL, g = NULL, b = 1))
}
```
```{r}
metrics <- paths %>%
  split(.$split) %>%
  map(~ metrics_fun(.)) %>%
  bind_rows(.id = "split")
head(metrics)
```

```{r}
metrics_ <- metrics %>%
  pivot_longer(precision:recall, names_to = "metric")

ggplot(metrics_, aes(x = threshold, y = value, col = split)) +
  geom_line(aes(group = path), size = 0.5, alpha = 0.6) +
  guides(col = guide_legend(override.aes = list(size = 5, alpha = 1))) +
  scale_color_brewer(palette = "Set2") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_grid(metric ~ class) +
  theme(
    legend.position = "bottom",
    panel.border = element_rect(fill = "NA", size = .5)
  )
```

```{r}
metrics_ %>%
  group_by(metric, path, class) %>%
  summarise(mean = mean(value, na.rm = TRUE)) %>%
  arrange(class, metric, desc(mean))
```

```{r}
ims <- paths %>%
  filter(ix == 29, split == "test") %>%
  split(.$type) %>%
  map(~ load_npy(.$path[1]))

p <- list(
  plot_rgb(ims[["x"]], c(5, 4, 2), r = 1, g = 2, b = 3),
  plot_rgb(ims[["x"]], c(13, 13, 13)),
  plot_rgb(ims[["y_hat"]], r = NULL),
  plot_rgb(ims[["y"]], r = NULL)
)
grid.arrange(grobs = p, ncol = 2)
```
