---
title: "Data Preparation"
description: |
  Generating data for model training.
author:
  - name: Kris Sankaran
    affiliation: UW Madison
date: "`r Sys.Date()`"
output: distill::distill_article
params:
  raw_dir: "/data/raw"
  out_dir: "/data/processed/train/"
  basins: "https://uwmadison.box.com/shared/static/2ptmi9b4gt5d5vyusju5u8kn5n1s6hnd.csv"
  # basins: https://uwmadison.box.com/shared/static/iilcsf3bbois8tmt7pklriu219s4wlu6.csv for test basins
  n_patches: 2000
---

Rscript -e "rmarkdown::render('data-preparation.Rmd', params = list(data_dir = '/datadrive/glaciers/unique_tiles/warped', out_dir = '/datadrive/glaciers/mappingvis/processed2/', basins = '/datdrive/glaciers/mappingvis/train_list.csv', n_patches = 3000))"

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library("abind")
library("dplyr")
library("purrr")
library("raster")
library("reticulate")
library("sf")
library("stringr")
library("tidyr")
use_condaenv("notebook")
source("data.R")
theme_set(theme_bw())
```

```{r}
vrt_path <- file.path(params$raw_dir, "region.vrt")
y_path <- file.path(params$raw_dir, "glaciers.geojson")

x <- brick(vrt_path)
basins <- read_csv(params$basins)
y <- read_sf(y_path) %>%
  filter(Sub_basin %in% basins$Sub_basin) %>%
  filter(Latitude > 1) %>% # seems like missing data set to 1
ys <- y %>%
  split(.$Glaciers)
```

We'll train using glaciers from the Dudh Koshi basin, and test using those from
the Sun Koshi basin.

```{r eval = FALSE}
tm_shape(y) +
  tm_fill(col = "Glaciers", palette = c("#93b9c3", "#4e326a"))
```

```{r}
coords <- y %>%
  as.data.frame() %>%
  dplyr::select(Longitude, Latitude) %>%
  as.matrix()

k_centers <- kmeans(coords, params$n_patches)$centers %>%
  as.data.frame() %>%
  mutate(type = "centroid")

ggplot(y, aes(x = Longitude, y = Latitude)) +
  geom_point(aes(col = Glaciers), size = 0.6) +
  geom_point(data = k_centers, col = "red", size = 0.1, alpha = 0.4) +
  scale_color_manual(values = c("#93b9c3", "#4e326a"))
```

```{r}
k_mat <- k_centers %>%
  dplyr::select(Longitude, Latitude) %>%
  as.matrix()
write_patches(params$x_path, ys, k_mat, params$out_dir)
```

```{r}
unlink(params$raw_dir, recursive = TRUE, force = TRUE)
```

